export interface IRestaurant {
  id: number;
  name: string;
  ar_name: string;
  description: string;
  location_id: number | null;
  hashtag: string;
  logo: string;
  image: string;
  placeholder_image: string;
  rating: string;
  delivery_time: string;
  delivery_time_label: string;
  pickup_time_label: string;
  price_range: number | null;
  is_pureveg: 0 | 1;
  slug: string;
  latitude: string;
  longitude: string;
  restaurant_charges: string | null;
  delivery_charges: string | null;
  address: string;
  ar_address: string;
  phone_number: string;
  email_address: string;
  sub_merchant_id: string;
  pincode: string | null;
  landmark: unknown;
  sku: string;
  is_busy: 0 | 1;
  busy_until: unknown;
  is_active: 0 | 1;
  is_accepted: 0 | 1;
  is_featured: 0 | 1;
  has_offer: 0 | 1;
  disabled_cod: 0 | 1;
  accept_preorder: 0 | 1;
  free_delivery_by_restaurant: 0 | 1;
  free_delivery_by_sweetat: 0 | 1;
  commission_rate_pickup: string;
  commission_rate_delivery: string;
  commission_rate_sweetat: string;
  delivery_type: number; // need explanation
  deliver_all_orders: 0 | 1;
  delivery_radius_from: string;
  delivery_radius_to: string;
  deliverable_by_sweetat: 0 | 1;
  sweetat_delivery_radius_from: string;
  sweetat_delivery_radius_to: string;
  delivery_charge_type: string;
  base_delivery_charge: number | null;
  base_delivery_distance: number | null;
  extra_delivery_charge: number | null;
  extra_delivery_distance: number | null;
  min_order_price: string;
  sweetat_min_order_price: string;
  is_notifiable: 0 | 1;
  auto_acceptable: 0 | 1;
  schedule_data: string;
  is_schedulable: 0 | 1;
  order_column: number;
  custom_message: string | null;
  distance: number;
  is_operational: boolean;
  order_ratings: IORDER_RATING;
}
export type IORDER_RATING = {
  _count: number | null;
  _packaging: number | null;
  _delivery_time: number | null;
  _pricing: number | null;
  _food_quality: number | null;
  _delivery_guy: number | null;
};
